"""Definición de columnas físicas ``margesi`` (alineado a Laravel ``Item``)."""

from __future__ import annotations

import sqlalchemy as sa

# (nombre_columna, tipo SQLAlchemy, nullable, server_default)
# Longitudes ampliadas respecto al legacy Laravel para datos reales en ``extra``.
MARGESI_STRING_COLS: tuple[tuple[str, int | None], ...] = (
    ("mar_nant", 30),
    ("mar_num", 30),
    ("mar_npri", 30),
    ("mar_ccat", 12),
    ("mar_cpat", 20),
    ("mar_des", 120),
    ("mar_esp", 100),
    ("mar_col", 100),
    ("mar_mar", 200),
    ("mar_mod", 100),
    ("mar_ser", 100),
    ("mar_med", 100),
    ("mar_tip", 100),
    ("mar_npla", 30),
    ("mar_nmot", 50),
    ("mar_ncha", 50),
    ("mar_ano", 10),
    ("mar_obs", 200),
    ("mar_eti", 10),
    ("mar_flag", 5),
    ("mar_foto", 200),
    ("mar_foto2", 200),
    ("amb_cod", 20),
    ("usu_cod", 20),
    ("usu_resp_cod", 20),
    ("cct_cod", 20),
    ("inv_sit", 15),
    ("inv_con", 10),
    ("inv_sit_ant", 50),
    ("inv_ver_sit", 50),
    ("inv_ver_obs", 500),
    ("user_create", 20),
    ("local_libre", 500),
    ("ccosto_libre", 500),
    ("ambiente_libre", 500),
    ("usuario_libre", 500),
    ("campo_libre", 500),
    ("mar_sit_conta", 50),
    ("mar_ing_tip", 50),
    ("mar_ing_fuente", 100),
    ("mar_ing_gasto", 100),
    ("mar_ing_siaf", 50),
    ("mar_ing_dini", 100),
    ("mar_ing_dadq", 100),
    ("mar_ing_ding", 100),
    ("mar_ing_cta", 50),
    ("mar_ing_dasi", 100),
    ("mar_tas_doc", 100),
    ("mar_rev_doc", 100),
    ("mar_cont_doc", 100),
    ("mar_cont_cta", 50),
    ("mar_sit_gral", 50),
    ("mar_baj_causal", 100),
    ("mar_baj_res", 100),
    ("mar_baj_tdisp", 100),
    ("mar_baj_rdis", 100),
    ("mar_baj_benef", 200),
    ("mar_baj_elim_x", 500),
)

MARGESI_ENUM_COLS: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("mar_est", ("N", "B", "R", "M", "I"), "B"),
    ("mar_uso", ("S", "N"), "S"),
    ("mar_seg", ("S", "N"), "S"),
)

MARGESI_INT_COLS = ("inv_num", "inv_hoj", "inv_num_1", "inv_num_2")

MARGESI_DATE_COLS = (
    "mar_ing_fdini",
    "mar_ing_fdadq",
    "mar_ing_fding",
    "mar_ing_fdasi",
    "mar_tas_fec",
    "mar_rev_fec",
    "mar_cont_fec",
    "mar_baj_fres",
    "mar_baj_fdis",
    "inv_ver_fecha",
)

MARGESI_DECIMAL_COLS = (
    "mar_ing_val",
    "mar_ing_vdep",
    "mar_ing_vutil",
    "mar_ing_pdep",
    "mar_ing_edad",
    "mar_tas_val",
    "mar_tas_vutil",
    "mar_rev_vutil",
    "mar_rev_pdep",
    "mar_rev_edad",
    "mar_rev_vdep",
    "mar_cont_val",
    "mar_cont_vutil",
    "mar_cont_pdep",
    "mar_cont_edad",
    "mar_cont_depm",
    "mar_dep_hist",
    "mar_net_hist",
    "mar_dep_acum",
    "mar_net_val",
    *tuple(f"mar_dep_m{i:02d}" for i in range(1, 14)),
)

# Mapeo claves legacy ``extra`` / formulario React → columna física
EXTRA_KEY_TO_COLUMN: dict[str, str] = {
    "codigo_anterior": "mar_nant",
    "codigo_interno": "mar_num",
    "codigo_bien_principal": "mar_npri",
    "codigo_tipo_bien_sbn": "mar_cpat",
    "mar_ccat": "mar_ccat",
    "especificacion_descripcion": "mar_esp",
    "estado_conservacion": "mar_est",
    "operatividad": "mar_uso",
    "operativo": "mar_uso",
    "seguridad": "mar_seg",
    "color": "mar_col",
    "marca": "mar_mar",
    "modelo": "mar_mod",
    "serie": "mar_ser",
    "medidas": "mar_med",
    "tipo": "mar_tip",
    "num_placa": "mar_npla",
    "num_motor": "mar_nmot",
    "num_chasis": "mar_ncha",
    "anio": "mar_ano",
    "observacion_bien": "mar_obs",
    "flag_etiquetado": "mar_eti",
    "mar_eti": "mar_eti",
    "flag_libre": "mar_flag",
    "foto_bien": "mar_foto",
    "foto2_bien": "mar_foto2",
    "codigo_ambiente": "amb_cod",
    "codigo_usuario": "usu_cod",
    "codigo_usuario_responsable": "usu_resp_cod",
    "codigo_centro_costo": "cct_cod",
    "situacion_contable": "mar_sit_conta",
    "tipo_ingreso": "mar_ing_tip",
    "fuente_financiamiento": "mar_ing_fuente",
    "partida_presupuestal": "mar_ing_gasto",
    "siaf": "mar_ing_siaf",
    "doc_inicial_adquisicion": "mar_ing_dini",
    "fecha_doc_inicial": "mar_ing_fdini",
    "doc_adquisicion": "mar_ing_dadq",
    "fecha_doc_adquisicion": "mar_ing_fdadq",
    "doc_ing_almacen": "mar_ing_ding",
    "fecha_doc_ing_almacen": "mar_ing_fding",
    "valor_ingresar_bien": "mar_ing_val",
    "depreciacion_ingresar": "mar_ing_vdep",
    "vida_util_total_ingreso_meses": "mar_ing_vutil",
    "pct_depreciacion_ingreso": "mar_ing_pdep",
    "edad_ingreso_meses": "mar_ing_edad",
    "cuenta_contable_ingresar": "mar_ing_cta",
    "doc_asignacion_inicial": "mar_ing_dasi",
    "fecha_doc_asignacion_inicial": "mar_ing_fdasi",
    "doc_tasacion": "mar_tas_doc",
    "fecha_tasacion": "mar_tas_fec",
    "valor_tasacion": "mar_tas_val",
    "vida_util_tasacion_meses": "mar_tas_vutil",
    "doc_revaluacion": "mar_rev_doc",
    "fecha_revaluacion": "mar_rev_fec",
    "vida_util_revaluacion_meses": "mar_rev_vutil",
    "pct_depreciacion_revaluacion": "mar_rev_pdep",
    "edad_revaluacion_meses": "mar_rev_edad",
    "valor_depreciacion_fecha_revaluacion": "mar_rev_vdep",
    "documento_contable": "mar_cont_doc",
    "fecha_documento_contable": "mar_cont_fec",
    "valor_contable": "mar_cont_val",
    "cuenta_contable": "mar_cont_cta",
    "vida_util_meses": "mar_cont_vutil",
    "pct_depreciacion_anual": "mar_cont_pdep",
    "edad_ultimo_cierre": "mar_cont_edad",
    "depreciacion_mensual": "mar_cont_depm",
    "depreciacion_historica": "mar_dep_hist",
    "valor_neto_historico": "mar_net_hist",
    "depreciacion_acumulada_actual": "mar_dep_acum",
    "valor_neto_actual": "mar_net_val",
    "situacion_general_contable": "mar_sit_gral",
    "causal_baja": "mar_baj_causal",
    "resolucion_baja": "mar_baj_res",
    "fecha_baja": "mar_baj_fres",
    "tipo_disposicion": "mar_baj_tdisp",
    "resolucion_disposicion": "mar_baj_rdis",
    "fecha_disposicion": "mar_baj_fdis",
    "beneficiario": "mar_baj_benef",
    "razon_eliminacion": "mar_baj_elim_x",
    "situacion_inventario": "inv_sit",
    "situacion_verificacion": "inv_ver_sit",
    "fecha_verificacion": "inv_ver_fecha",
    "observacion_verificacion": "inv_ver_obs",
}

for i in range(1, 14):
    EXTRA_KEY_TO_COLUMN[f"mar_dep_m{i:02d}"] = f"mar_dep_m{i:02d}"


MARGESI_STRING_MAX: dict[str, int] = {name: length for name, length in MARGESI_STRING_COLS if length}


def all_margesi_column_names() -> list[str]:
    names: list[str] = [c[0] for c in MARGESI_STRING_COLS]
    names.extend(c[0] for c in MARGESI_ENUM_COLS)
    names.extend(MARGESI_INT_COLS)
    names.extend(MARGESI_DATE_COLS)
    names.extend(MARGESI_DECIMAL_COLS)
    return names
